dist: xenial

language: minimal

services:
  - docker

# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

env:
  global:
    - ERLANGVERSION=20.3.8.25-1
    - TARBALL_URL=https://dist.apache.org/repos/dist/release/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz
    - TARBALL=apache-couchdb-3.1.1.tar.gz
  matrix:
    - TARGET="js debian-stretch"
    - TARGET="couch debian-stretch ${TARBALL_URL}"
    - TARGET="js debian-buster"
    - TARGET="couch debian-buster ${TARBALL_URL}"
    # Too slow, have to comment out...
    #- TARGET="js arm64v8-debian-buster"
    #- TARGET="couch arm64v8-debian-buster ${TARBALL_URL}"
    - TARGET="js ubuntu-xenial"
    - TARGET="couch ubuntu-xenial ${TARBALL_URL}"
    - TARGET="js ubuntu-bionic"
    - TARGET="couch ubuntu-bionic ${TARBALL_URL}"
    - TARGET="js centos-6"
    - TARGET="couch centos-6 ${TARBALL_URL}"
    - TARGET="js centos-7"
    - TARGET="couch centos-7 ${TARBALL_URL}"
    - TARGET="js centos-8"
    - TARGET="couch centos-8 ${TARBALL_URL}"

before_install:
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

script:
  - ERLANGVERSION=${ERLANGVERSION} ./build.sh ${TARGET}

after_script:
  - ls -laR pkgs/
