dist: xenial

language: minimal

services:
  - docker

# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

env:
  global:
    - ERLANGVERSION=19.3.6
    - TARBALL_URL=https://dist.apache.org/repos/dist/release/couchdb/source/2.3.1/apache-couchdb-2.3.1.tar.gz
    - TARBALL=apache-couchdb-2.3.1.tar.gz
  matrix:
    - TARGET="js debian-stretch"
    - TARGET="couch debian-stretch ${TARBALL_URL}"
    - ERLANGVERSION=20.3.8.20 TARGET="js aarch64-debian-stretch"
    - ERLANGVERSION=20.3.8.20 TARGET="couch aarch64-debian-stretch ${TARBALL_URL}"
    - ERLANGVERSION=20.3.8.22-1 TARGET="js debian-buster"
    - ERLANGVERSION=20.3.8.22-1 TARGET="couch debian-buster ${TARBALL_URL}"
    - TARGET="js ubuntu-xenial"
    - TARGET="couch ubuntu-xenial ${TARBALL_URL}"
    - TARGET="js ubuntu-bionic"
    - TARGET="couch ubuntu-bionic ${TARBALL_URL}"
    - TARGET="js centos-6"
    - TARGET="couch centos-6 ${TARBALL_URL}"
    - TARGET="js centos-7"
    - TARGET="couch centos-7 ${TARBALL_URL}"

before_install:
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - ERLANGVERSION=${ERLANGVERSION} ./build.sh ${TARGET}

after_script:
  - ls -laR pkgs/
