#!/bin/sh

# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

if [ -z ${SNAP_INSTANCE_KEY} ]
then
    SNAP_INSTANCE_DATA=${SNAP_DATA}
    SNAP_INSTANCE_COMMON=${SNAP_COMMON}
else
    SNAP_INSTANCE_DATA=$(echo ${SNAP_DATA} | sed -e s/${SNAP_NAME}/${SNAP_INSTANCE_NAME}/)
    SNAP_INSTANCE_COMMON=$(echo ${SNAP_COMMON} | sed -e s/${SNAP_NAME}/${SNAP_INSTANCE_NAME}/)
fi

mkdir -p ${SNAP_INSTANCE_DATA}/etc
mkdir -p ${SNAP_INSTANCE_COMMON}/data/nouveau

## If nouveau yaml file is there, copy to cfg directory (without overwriting)
NOUVEAU_CFG=${SNAP_INSTANCE_DATA}/etc/nouveau.yaml
if [ -s ${SNAP}/etc/nouveau.yaml ] && [ ! -s ${NOUVEAU_CFG} ]; then
   cat ${SNAP}/etc/nouveau.yaml > ${NOUVEAU_CFG}
   index_line=$(echo "${SNAP_INSTANCE_COMMON}/data/nouveau" | sed 's/\//\\\//g')
   sed --in-place "s/{{nouveau_index_dir}}/${index_line}/" ${NOUVEAU_CFG}
   sed --in-place "s/{{nouveau_port}}/${COUCHDB_NOUVEAU_PORT}/" ${NOUVEAU_CFG}
   sed --in-place "s/{{nouveau_admin_port}}/${COUCHDB_NOUVEAU_ADMIN_PORT}/" ${NOUVEAU_CFG}
fi