---
name: couchdb
version: 3.3.3
type: app
base: core22
license: Apache-2.0
summary: Official Apache CouchDB snap - a clustering document oriented database
description: |
  CouchDB is a database that completely embraces the web. Store your data with
  JSON documents. Access your documents and query your indexes with your web
  browser, via HTTP. Index, combine, and transform your documents with
  JavaScript.
assumes: [command-chain, common-data-dir]
grade: stable
confinement: strict

architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

parts:
  couchdb:
    plugin: make
    source: https://dlcdn.apache.org/couchdb/source/3.3.3/apache-couchdb-3.3.3.tar.gz
    source-type: tar
    override-build: ./configure --spidermonkey-version 91 && make release && cp -r rel/couchdb/* $SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - g++
      - libc6-dev
      - libcurl4-openssl-dev
      - libicu-dev
      - icu-devtools
      # For erlang/rebar processing
      - erlang-dev
      - erlang-base
      - erlang-reltool
      - erlang-nox
      - erlang-eunit
      - erlang-os-mon
      - erlang-syntax-tools
      # mozjs
      - libmozjs-91-dev
      # For fauxton
      - libnode-dev
      - npm
    stage-packages:
      - procps
      - libcurl4
      - libicu70
      - libmozjs-91-0
      - libssl3
      - libtinfo5
    stage:
      - -usr/share/doc
      - -usr/share/man
      - -var

environment:
  COUCHDB_ARGS_FILE: ${SNAP_DATA}/etc/vm.args
  COUCHDB_FAUXTON_DOCROOT: ${SNAP}/share/www
  COUCHDB_QUERY_SERVER_JAVASCRIPT: ${SNAP}/bin/couchjs ${COUCHJS_ARGS} ${SNAP}/share/server/main.js
  COUCHDB_QUERY_SERVER_COFFEESCRIPT: ${SNAP}/bin/couchjs ${COUCHJS_ARGS} ${SNAP}/share/server/main-coffee.js
  COUCHDB_INI_FILES: ${SNAP}/etc/default.ini ${SNAP}/etc/default.d ${SNAP_DATA}/etc/local.ini ${SNAP_DATA}/etc/local.d

apps:
  couchdb:
    command: bin/couchdb
    plugs: [network, network-bind, mount-observe]
  server:
    daemon: simple
    command: bin/couchdb
    plugs: [network, network-bind, mount-observe]
  remsh:
    command: bin/remsh
    plugs: [network, network-bind]
  couchjs:
    command: bin/couchjs
    plugs: [network, network-bind]
