name: couchdb-sklassen
version: 3.2.2
base: core20
build-base: core18
summary: Official Apache CouchDB snap - a clustering document oriented database
description: |
  CouchDB is a database that completely embraces the web. Store your data with
  JSON documents. Access your documents and query your indexes with your web
  browser, via HTTP. Index, combine, and transform your documents with
  JavaScript.

architectures:
  - build-on: amd64
    run-on: amd64
assumes: [command-chain, common-data-dir]
grade: stable
confinement: strict

parts:
  couchdb:
    plugin: make
    source: https://dlcdn.apache.org/couchdb/source/3.2.2/apache-couchdb-3.2.2.tar.gz
    source-type: tar
    override-build: |
            ./configure --prefix=$SNAPCRAFT_PART_INSTALL --disable-docs --spidermonkey-version 91
            make release
            cp -r rel/couchdb/* $SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - g++
      - libc6-dev
      - libcurl4-openssl-dev
      - libicu-dev
      - icu-devtools
      # For erlang/rebar processing
      - erlang-dev
      - erlang-base
      - erlang-reltool
      - erlang-nox
      - erlang-eunit
      - erlang-os-mon
      - erlang-syntax-tools
      # mozjs
      - libmozjs-91-dev
      # For fauxton
      - libnode-dev
      - npm
    stage-packages:
      - procps
      - libcurl4
      - libicu70
      - libmozjs-91-0
      - libssl3
      - libtinfo5
    stage:
      - -usr/share/doc
      - -usr/share/man
      - -var
    override-stage: |
      # focal libmozjs is busted...
      #cd ${SNAPCRAFT_PART_INSTALL}/usr/lib/x86_64-linux-gnu/
      #ln -s libmozjs-68.so.68.6.0 libmozjs-68.so.0
      snapcraftctl stage

environment:
  COUCHDB_ARGS_FILE: ${SNAP_DATA}/etc/vm.args
  COUCHDB_FAUXTON_DOCROOT: ${SNAP}/share/www
  COUCHDB_QUERY_SERVER_JAVASCRIPT: ${SNAP}/bin/couchjs ${COUCHJS_ARGS} ${SNAP}/share/server/main.js
  COUCHDB_QUERY_SERVER_COFFEESCRIPT: ${SNAP}/bin/couchjs ${COUCHJS_ARGS} ${SNAP}/share/server/main-coffee.js
  ERL_FLAGS: "-couch_ini ${SNAP}/etc/default.ini
                         ${SNAP}/etc/default.d
                         ${SNAP_DATA}/etc/local.ini
                         ${SNAP_DATA}/etc/local.d"

apps:
  couchdb:
    adapter: full
    command: bin/couchdb
    plugs: [network, network-bind, mount-observe]
  server:
    daemon: simple
    adapter: full
    command: bin/couchdb
    plugs: [network, network-bind, mount-observe]
  remsh:
    command: bin/remsh
    plugs: [network, network-bind]
  couchjs:
    command: bin/couchjs
    plugs: [network, network-bind]
