name: couchdb
version: 2.0
summary: Document based database
description: CouchDB is a database that completely embraces the web. Store your data with JSON documents. Access your documents and query your indexes with your web browser, via HTTP. Index, combine, and transform your documents with JavaScript. 
confinement: strict
grade: stable

apps:
    server:
        daemon: simple
        command: rel/couchdb/bin/snap_run
        plugs: [network-bind, process-control, mount-observe, browser-support]
    couchdb:
        command: rel/couchdb/bin/snap_run
        plugs: [network-bind]
parts:
    couchdb: 
        plugin: make
        #source: http://www-us.apache.org/dist/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz
        source: https://github.com/apache/couchdb.git
        source-type: git
        source-tag: 2.1.0
        prepare: |
          ./configure --disable-docs
        build: |
          make release
          cp -ra ./rel $SNAPCRAFT_PART_INSTALL
          cp -ra ./bin $SNAPCRAFT_PART_INSTALL
        build-packages:
          - binutils
          - libc6-dev
          - gcc
          - g++
          - make
          - erlang-dev
          - erlang-base
          - erlang-reltool
          - libcurl4-openssl-dev
          - libmozjs185-dev
          - libnspr4-dev
          - libicu-dev
          - icu-devtools
          # For erlang/rebar processing
          - erlang-nox
          - erlang-os-mon
          - erlang-syntax-tools
          # For fauxton
          - nodejs-dev
          - nodejs-legacy
          - npm
        stage:
            - rel
            - bin
        prime:
            - rel
            - bin

    snap-config:
        plugin: dump
        source: ./snap/
        organize:
            snap.ini: rel/couchdb/etc/snap.ini
            snap_run: rel/couchdb/bin/snap_run

    erlang:
        plugin: nil
        stage-packages:
            - erlang-base
            - erlang-crypto
            - erlang-eunit
            - erlang-inets
            - erlang-os-mon
            - erlang-public-key
            - erlang-ssl
            - erlang-syntax-tools
            - erlang-tools
            - erlang-xmerl
            - libc6
            - libcurl3
            - libgcc1
            - libicu55
            - libmozjs185-1.0
            - libstdc++6
        
