#!/bin/sh

# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

mkdir -p ${SNAP_COMMON}/data

mkdir -p ${SNAP_DATA}/etc/local.d

if [ ! -s ${SNAP_DATA}/etc/vm.args ]; then
   cat ${SNAP}/etc/vm.args > ${SNAP_DATA}/etc/vm.args
fi

LOCAL_INI=$SNAP_DATA/etc/local.ini
if [ ! -s ${LOCAL_INI} ]; then
   cat ${SNAP}/etc/local.ini > ${LOCAL_INI}
fi

# Ensure that local.ini has the view_index_dir specified
if ! $(grep -q "^view_index_dir" ${LOCAL_INI}); then
    view_line=$(echo "view_index_dir = ${SNAP_COMMON}/data" | sed 's/\//\\\//g')
    sed --in-place "/^\[couchdb\].*$/a ${view_line}" ${LOCAL_INI} 2>/dev/null
fi

# Ensure that local.ini has the database_dir specified
if ! $(grep -q "^database_dir" ${LOCAL_INI}); then
    database_line=$(echo "database_dir = ${SNAP_COMMON}/data" | sed 's/\//\\\//g')
    sed --in-place "/^\[couchdb\].*$/a ${database_line}" ${LOCAL_INI} 2>/dev/null
fi

