#!/bin/sh

# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# If the data directory does not exisit in /var/couchdb/common; but does exisit in /var/couchdb/current; move it to common.

if [ ! -d ${SNAP_COMMON}/data ]; then
   if [ -d ${SNAP_DATA}/data ]; then
       mv ${SNAP_DATA}/data ${SNAP_COMMON}/data
   fi
fi

